import pandas as pd
data=pd.read_csv('C:/Users/vjaat/Downloads/01.Data Cleaning and Preprocessing.csv')
print(type(data))
print("next step data")
print(data.info)
print("next step data")
print(data.describe())
print("next step data")
print(data.drop_duplicates())
print("next step data")
print(data.isnull())
print("next step data")
print(data.isnull().sum())
print("next step data")
print(data.isnull().sum().sum())
print("next step data")
print(data.fillna(value=0))
print("next step data")
print(data.fillna(method='pad'))
print("next step data")
print(data.fillna(method='bfill'))
print("next step data")
import numpy as np
from scipy import stats
print(data.columns)
print("next step data")
print(data.drop(['Observation'],axis=1,inplace=True))
print("next step data")
print(data.columns)
print("next step data")
q1=data.quantile(0.75)
q2=data.quantile(0.25)
IQR=q1-q2
print(IQR)
print("next step data")
data2=data[~((data<(q2-1.5*IQR))|(data>(q1+1.5*IQR))).any(axis=1)]
print(data2)
print("end of result")